[package]
name = 'pallet-runtime-circuit'
authors = ['Maciej Baj <https://github.com/MaciejBaj>']
description = 'Circuit Runtime for composable smart contracts execution over Gateways'
edition = '2018'
homepage = 'https://github.com/t3rn/t3rn'
license = 'Apache 2.0'
repository = 'https://github.com/t3rn/t3rn.git'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.5", features = ['derive', 'full'], default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
sp-keyring = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
sp-wasm-interface = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
pallet-sudo = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }

serde = { version = "1.0.101", features = ["derive"], default-features = false}
serde_json = { version = "1.0"}
impl-serde = { version = "0.3.1" }
env_logger = { version = "0.7.1" }
anyhow = { version = "1.0.26" }
async-std = { version = "1.6.2" }
regex = { version = "1" }
reduce = { version = "0.1" }
t3rn-primitives = { version = "0.1.0", path = "../primitives", default-features = false }
#gateway-escrow-engine = { version = "0.3.0", path = "../../../gateway/pallet-escrow-gateway/escrow-engine", default-features = false }
#versatile-wasm = { version = "0.3.0", path = "../../../gateway/pallet-escrow-gateway/escrow-engine/versatile-wasm", default-features = false }
#subxt = { package = "substrate-subxt", version = "0.12.0", path = "../../../sdk/subxt" }

[dev-dependencies]
wat = { version = "1.0", default-features = false }
#sp-io = {version = '2.0.0', default-features = false}

[features]
default = ['std']
std = [
    'codec/std',
    'sp-core/std',
    'sp-std/std',
#    'sp-keyring/std',
    'sp-wasm-interface/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-sudo/std',
    'pallet-balances/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment/std',
    'pallet-randomness-collective-flip/std',
    't3rn-primitives/std',
#    'gateway-escrow-engine/std',
#    'versatile-wasm/std',
#    'subxt/std',
]
