[package]
name = "pallet-circuit-execution-delivery"
version = "0.1.0"
authors = ["Maciej Baj <maciej@t3rn.io>"]
edition = "2018"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME example pallet for offchain worker"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
t3rn-primitives = { version = "0.1.0", default-features = false, path = "../primitives" }
serde = { version = "1.0.124", optional = true }
lite-json = { version = "0.1", default-features = false }
log = { version = "0.4.14", default-features = false }
regex = { version = "1" }
sp-keystore = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git", branch = "master" , optional = true }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"  }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"  }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master" }

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "serde",
    "sp-keystore",
    "lite-json/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "t3rn-primitives/std",
    "log/std",
]
try-runtime = ["frame-support/try-runtime"]