sudo: false
language: rust

cache:
  # Don't use `cache: cargo` since it adds the `target` directory and that can be huge.
  # Saving and loading this directory dwarfes actual compilation and test times. But what is more
  # important, is that travis timeouts the build since the job doesn't produce any output for more
  # than 10 minutes.
  #
  # So we just cache ~/.cargo directory
  directories:
    - /home/travis/.cargo

matrix:
  fast_finish: false
  include:
    - rust: nightly-2020-08-04

before_script:
  - rustup toolchain install nightly-2020-08-04
  - rustup target add wasm32-unknown-unknown --toolchain nightly-2020-08-04
  - git submodule update

script:
  - cd gateway || exit $?
  - echo -e "\033[0;34mBuilding escrow pallets..."
#  Comment out builds on travis bc of timeout.
#  - cd pallet-escrow-gateway/escrow-engine && cargo build || (cargo update && cargo build) || exit $? && cd ../..
#  - cd pallet-escrow-gateway/escrow-engine/versatile-wasm && cargo build || (cargo update && cargo build) || exit $? && cd ../../..
#  - cd pallet-escrow-gateway/escrow-engine/escrow-contracts-wrapper && cargo build || (cargo update && cargo build) || exit $? && cd ../../..
#  - cd pallet-escrow-gateway/runtime-gateway && cargo build || (cargo update && cargo build) || exit $? && cd ../..
#  - cd pallet-escrow-gateway/contracts-gateway && cargo build || (cargo update && cargo build) || exit $? && cd ../..
  - echo -e "\033[0;32mTesting gateway pallets..."
  - cd pallet-escrow-gateway/escrow-engine && cargo test; cd ../..
  - cd pallet-escrow-gateway/runtime-gateway && cargo test; cd ../..
  - cd pallet-escrow-gateway/contracts-gateway && cargo test; cd ../..
  - echo -e "\033[0;34mBuilding runtimes with escrow pallets..."
  - echo -e "\033[0;34mBuilding node-tiny..."
  - cd node-tiny && cargo build || (cargo update && cargo build) || exit $? && cd ..
