[package]
authors = ['Maciej Baj <https://github.com/MaciejBaj>']
description = 'Gateway for multi-phase contracts execution secured by escrow accounts'
edition = '2018'
homepage = 'https://github.com/t3rn/t3rn'
license = 'Apache 2.0'
name = 'escrow-gateway'
repository = 'https://github.com/t3rn/escrow-gateway'
version = '2.0.0-rc5'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.1'

[dependencies.escrow-gateway-primitives]
default-features = false
path = 'common'
version = '0.1.0-rc0'

#[dependencies.escrow-gateway-api]
#default-features = false
#path = 'api'
#version = '0.1.0-rc0'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'

version = '2.0.0-rc5'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'

version = '2.0.0-rc5'

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
#    'escrow-gateway-primitives/std',
]
