[package]
name = "circuit-rpc-runtime-api"
version = "0.1.0"
authors = ["MaciejBaj <maciej@maciejbaj.com>"]
edition = "2018"
homepage = "https://t3rn.io"
license = "Apache 2.0"
repository = "https://github.com/t3rn/t3rn/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api ={ git = "https://github.com/paritytech/substrate.git", tag = 'monthly-2021-06' }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
sp-std = { git = "https://github.com/paritytech/substrate.git", tag = 'monthly-2021-06' }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", tag = 'monthly-2021-06' }
t3rn-primitives = { version = "0.1.0", path = "../../primitives" }

[features]
default = ["std"]
std = [
	"sp-api/std",
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
]
