[package]
authors     = [ "t3rn ltd. <team@t3rn.io>" ]
description = "A crate that hosts a common definitions that are relevant for t3rn components."
edition     = "2021"
homepage    = "https://t3rn.io"
license     = "Apache 2.0"
name        = "t3rn-types"
repository  = "https://github.com/t3rn/t3rn/"
version     = "1.0.0-alpha.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde                 = { default-features = false, version = "1.0", optional = true, features = ["derive"] }
scale-info            = { version = "2", default-features = false, features = [ "derive" ] }
codec                 = { package = "parity-scale-codec", version = "3", default-features = false, features = [ "derive" ] }

sp-runtime            = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.19', default-features = false, optional = true }
sp-core            = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.19', default-features = false, optional = true }
sp-io            = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.19', default-features = false, optional = true }
primitive-types       = { git = "https://github.com/paritytech/parity-common.git", default-features = false, features = ["scale-info"] }

[dev-dependencies]
hex         = "0.4"
hex-literal = { version = '0.3.1' }
serde_json  = "1.0.41"

sp-runtime            = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.19' }
sp-core            = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.19' }

[features]
default = [ "std" ]
std = [
    "codec/std",
    "scale-info/std",
    "serde/std",
]
runtime = [
    "sp-runtime",
    "sp-core",
    "sp-io",
]
runtime-std = [
    "sp-runtime/std",
    "sp-core/std",
    "sp-io/std",
]