[package]
authors = ['Maciej Baj <https://github.com/MaciejBaj>']
description = 'Gateway for multi-phase contracts execution secured by escrow accounts'
edition = '2018'
homepage = 'https://github.com/t3rn/t3rn'
license = 'Apache 2.0'
name = 'pallet-runtime-gateway'
repository = 'https://github.com/t3rn/t3rn.git'
version = '0.5.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
reduce = "0.1.4"
anyhow = "*"
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-support = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
frame-system = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-balances = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-sudo = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-timestamp = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-transaction-payment = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-randomness-collective-flip = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }

versatile-wasm = { version = "0.4.0", default-features = false, path = "../../../vm/versatile-wasm" }
t3rn-primitives = { version = "0.1.0", default-features = false, path = "../../../circuit/src/primitives" }

sp-std = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
sp-core = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
sp-wasm-interface = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }

sp-io = {version = '3.0.0', default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }

[dev-dependencies]
wat = { version = "1.0", default-features = false }
flipper = {version = '3.0.0', path = "fixtures/flipper", default-features = false}
weights = {version = '3.0.0', path = "fixtures/weights", default-features = false}

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-balances/std',
    'pallet-sudo/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment/std',
    'pallet-randomness-collective-flip/std',
    'versatile-wasm/std',
    't3rn-primitives/std',
    'sp-std/std',
    'sp-core/std',
    'sp-wasm-interface/std',
    'sp-runtime/std',
]
