[package]
name = "t3rn-primitives"
version = "0.1.0"
authors = ["MaciejBaj <maciej@maciejbaj.com>"]
edition = "2018"
homepage = "https://t3rn.io"
license = "Apache 2.0"
repository = "https://github.com/t3rn/t3rn/"
description = "A crate that hosts a common definitions that are relevant for the all t3rn pallets."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# This crate should not rely on any of the frame primitives.
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]  }
hex = { version = "0.4.3", default-features = false }
sp-std =  { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
sp-core =  { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master" }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master" }
pallet-sudo = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master" }

[dev-dependencies]
substrate-test-runtime = { git = 'https://github.com/paritytech/substrate.git', branch = "master" }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-core/std",
	"pallet-sudo/std",
	"frame-system/std",
	"frame-support/std",
	"hex/std"
]
