[package]
name = "escrow-gateway-api"
version = "0.1.0-rc0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Node-specific RPC methods for interaction with escrow gateway."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1" }
jsonrpc-core = "14.2.0"
jsonrpc-core-client = "14.2.0"
jsonrpc-derive = "14.2.1"
sp-blockchain = {  tag = "v2.0.0-rc5", git = 'https://github.com/paritytech/substrate.git' }
sp-core = { tag = "v2.0.0-rc5", git = 'https://github.com/paritytech/substrate.git' }
sp-rpc = {  tag = "v2.0.0-rc5", git = 'https://github.com/paritytech/substrate.git' }
serde = { version = "1.0.101", features = ["derive"] }
sp-runtime = { tag = "v2.0.0-rc5", git = 'https://github.com/paritytech/substrate.git'}
sp-api = {  tag = "v2.0.0-rc5", git = 'https://github.com/paritytech/substrate.git' }
pallet-contracts-primitives = {  tag = "v2.0.0-rc5", git = 'https://github.com/paritytech/substrate.git' }
#pallet-contracts-rpc-runtime-api = { tag = "v0.8.0-rc4", git = 'https://github.com/paritytech/substrate.git' }
pallet-contracts-rpc-runtime-api = "0.8.0-rc4"

[dev-dependencies]
serde_json = "1.0.41"
