[package]
authors = ['Maciej Baj <https://github.com/MaciejBaj>']
build = 'build.rs'
description = 'A FRAME-based Substrate "tiny" node, with the only extra being t3rn escrow gateway.'
edition = '2018'
license = 'Apache 2.0'
name = 'demo-runtime'
repository = 'https://github.com/t3rn/t3rn/tree/development/gateway/demo-runtime'
version = '2.0.0'

[[bin]]
name = 'demo-runtime'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = '2.0.0'

[dependencies]
jsonrpc-core = '15.0.0'
structopt = '0.3.8'

# local dependencies
node-demo-runtime = { path = '../runtime', version = '2.0.0' }

# Substrate dependencies
frame-benchmarking = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sc-cli = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06', features = ['wasmtime'] }
sc-client-api = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sc-consensus = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sc-executor = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06', features = ['wasmtime'] }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sc-rpc = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sc-service = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06', features = ['wasmtime'] }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sp-api = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sp-block-builder = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sp-blockchain = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sp-consensus = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sp-core = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sp-inherents = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sp-runtime = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
pallet-contracts = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }
pallet-contracts-rpc = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-06' }

[features]
default = []
runtime-benchmarks = ['node-demo-runtime/runtime-benchmarks']
