[package]
authors     = [ "t3rn ltd. <team@t3rn.io>" ]
description = "on-chain composable contracts registry"
edition     = "2018"
homepage    = "https://t3rn.io"
license     = "Apache 2.0"
name        = "pallet-circuit"
readme      = "README.md"
repository  = "https://github.com/t3rn/t3rn/"
version     = "1.0.0-alpha.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec              = { package = "parity-scale-codec", version = "2.2.0", default-features = false }
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17', optional = true }
frame-support      = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
frame-system       = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
log                = { version = "0.4.14", default-features = false }
pallet-timestamp   = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
scale-info         = { version = "1.0", default-features = false, features = [ "derive" ] }
serde              = { version = "1.0.136", optional = true, features = [ "derive" ] }
sp-io              = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
sp-runtime         = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
sp-std             = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
t3rn-primitives    = { path = "../../primitives", default-features = false }
t3rn-protocol      = { path = "../../protocol", default-features = false }

sp-core = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17', default-features = false }

orml-traits = { git = "https://github.com/t3rn/open-runtime-module-library", branch = "polkadot-v0.9.17", default-features = false }

[dev-dependencies]
frame-election-provider-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
pallet-authorship               = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.17' }
pallet-babe                     = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
pallet-multi-finality-verifier  = { default-features = false, path = "../multi-finality-verifier" }
pallet-offences                 = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
pallet-session                  = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
pallet-staking                  = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
pallet-staking-reward-curve     = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
sp-consensus-babe               = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.17' }
sp-consensus-vrf                = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.17' }
sp-finality-grandpa             = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.17' }
sp-staking                      = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.17' }

pallet-randomness-collective-flip = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.17' }
pallet-transaction-payment        = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.17' }

orml-tokens               = { git = "https://github.com/t3rn/open-runtime-module-library", branch = "polkadot-v0.9.17" }
pallet-balances           = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
pallet-sudo               = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }

pallet-xdns               = { path = "../../pallets/xdns" }
pallet-circuit-portal     = { path = "../circuit-portal" }
pallet-contracts-registry = { path = "../../pallets/contracts-registry" }

#snowbridge-basic-channel = { git = "https://github.com/t3rn/snowbridge", branch = "polkadot-v0.9.17", default-features = false }

[features]
default = [ "std" ]
runtime-benchmarks = [ "frame-benchmarking" ]
std = [
  "codec/std",
  "frame-benchmarking/std",
  "frame-support/std",
  "frame-system/std",
  "log/std",
  "pallet-timestamp/std",
  "serde/std",
  "sp-io/std",
  "sp-core/std",
  "sp-runtime/std",
  "sp-std/std",
  "t3rn-primitives/std",
  "t3rn-protocol/std",
  "scale-info/std",
  "orml-traits/std",
  "pallet-multi-finality-verifier/std",
  "frame-election-provider-support/std",
  "pallet-offences/std",
  "pallet-session/std",
  "pallet-staking/std",
  "pallet-authorship/std",
  "pallet-babe/std",
  "sp-staking/std",
  "sp-finality-grandpa/std",
  "sp-consensus-vrf/std",
  "sp-consensus-babe/std",
  "pallet-transaction-payment/std",
  "pallet-randomness-collective-flip/std",
  #    "snowbridge-basic-channel/std",
  #    pallet-staking-reward-curve not needed here
]
try-runtime = [ "frame-support/try-runtime" ]
