[package]
name = "pallet-contracts-registry-rpc"
version = "0.1.0"
authors = ["t3rn"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://t3rn.io"
repository = "https://github.com/t3rn/t3rn/"
description = "RPC interface for the contracts registry pallet."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
