[package]
authors = ['Maciej Baj <https://github.com/MaciejBaj>']
description = 'Gateway for multi-phase contracts execution secured by escrow accounts'
edition = '2018'
homepage = 'https://github.com/t3rn/t3rn'
license = 'Apache 2.0'
name = 'escrow-gateway'
repository = 'https://github.com/t3rn/escrow-gateway'
version = '2.0.0-rc4'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.1'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc4'
version = '2.0.0-rc4'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc4'
version = '2.0.0-rc4'


[dependencies.balances]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
tag = 'v2.0.0-rc4'
version = '2.0.0-rc4'
#
#[dependencies.contracts]
#git = 'https://github.com/paritytech/substrate.git'
#default-features = false
#package = 'pallet-contracts'
#tag = 'v2.0.0-rc4'
#version = '2.0.0-rc4'
#
#[dependencies.contracts-rpc-runtime-api]
#git = 'https://github.com/paritytech/substrate.git'
#default-features = false
#package = 'pallet-contracts-rpc-runtime-api'
#version = '0.8.0-rc4'
#tag = 'v2.0.0-rc4'
#
#[dependencies.contracts-primitives]
#git = 'https://github.com/paritytech/substrate.git'
#default-features = false
#package = 'pallet-contracts-primitives'
#tag = 'v2.0.0-rc4'
#version = '2.0.0-rc4'


[dev-dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc4'
version = '2.0.0-rc4'

[dev-dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc4'
version = '2.0.0-rc4'

[dev-dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc4'
version = '2.0.0-rc4'

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
]
